//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using Iesi.Collections;
using NHibernate.Connection;

namespace NHibernate.Test
{
    using System.Threading.Tasks;
    using System.Threading;
    public partial class DebugConnectionProvider : DriverConnectionProvider
    {

        public override async Task<DbConnection> GetConnectionAsync(CancellationToken cancellationToken)
        {
            var connection = await (base.GetConnectionAsync(cancellationToken));
            connections.Add(connection);
            return connection;
        }
    }
}