//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using System.Collections.Generic;
using System.IO;

using Lucene.Net.Analysis;
using Lucene.Net.Documents;
using Lucene.Net.Index;
using Lucene.Net.QueryParsers;
using Lucene.Net.Store;
using Lucene.Net.Util;
using NHibernate.Cfg;
using NHibernate.Search.Store;

using NUnit.Framework;

namespace NHibernate.Search.Tests.Shards
{
    using System.Threading.Tasks;
    [TestFixture]
    public class ShardsTestAsync : PhysicalTestCase
    {
        protected override IEnumerable<string> Mappings
        {
            get { return new[]
                             {
                             "Shards.Animal.hbm.xml", 
                             "Shards.Furniture.hbm.xml"
                             }; }
        }

        protected override bool RunFixtureSetUpAndTearDownForEachTest
        {
            get { return true; }
        }

        #region Tests

        [Test, Explicit]
        public async Task StandardBehaviorAsync()
        {
            ISession s = OpenSession();
            ITransaction tx = s.BeginTransaction();
            Animal a = new Animal();
            a.Id = 1;
            a.Name = "Elephant";
            await (s.PersistAsync(a));
            a = new Animal();
            a.Id = 2;
            a.Name = "Bear";
            await (s.PersistAsync(a));
            await (tx.CommitAsync());

            s.Clear();

            tx = s.BeginTransaction();
            a = (Animal) await (s.GetAsync(typeof(Animal), 1));
            a.Name = "Mouse";
            Furniture fur = new Furniture();
            fur.Color = "dark blue";
            await (s.PersistAsync(fur));
            await (tx.CommitAsync());

            s.Clear();

            tx = s.BeginTransaction();
            IFullTextSession fts = Search.CreateFullTextSession(s);
            QueryParser parser = new QueryParser(Version.LUCENE_30, "id", new StopAnalyzer(Version.LUCENE_30));

            IList results = await (fts.CreateFullTextQuery(parser.Parse("name:mouse OR name:bear")).ListAsync());
            Assert.AreEqual(2, results.Count, "Either double insert, single update, or query fails with shards");

            results = await (fts.CreateFullTextQuery(parser.Parse("name:mouse OR name:bear OR color:blue")).ListAsync());
            Assert.AreEqual(3, results.Count, "Mixing shared and non sharded properties fails");
            results = await (fts.CreateFullTextQuery(parser.Parse("name:mouse OR name:bear OR color:blue")).ListAsync());
            Assert.AreEqual(3, results.Count, "Mixing shared and non sharded properties fails with indexreader reuse");

            // cleanup
            await (s.DeleteAsync("from System.Object"));
            await (tx.CommitAsync());
            s.Close();
        }

        [Test, Explicit]
        public async Task InternalShardingAsync()
        {
            ISession s = OpenSession();
            ITransaction tx = s.BeginTransaction();
            Animal a = new Animal();
            a.Id = 1;
            a.Name = "Elephant";
            await (s.PersistAsync(a));
            a = new Animal();
            a.Id = 2;
            a.Name = "Bear";
            await (s.PersistAsync(a));
            await (tx.CommitAsync());

            s.Clear();
            IndexReader reader = IndexReader.Open(FSDirectory.Open(new DirectoryInfo(BaseIndexDir.FullName + "\\Animal00")), false);
            try
            {
                int num = reader.NumDocs();
                Assert.AreEqual(1, num);
            }
            finally
            {
                reader.Dispose();
            }

            reader = IndexReader.Open(FSDirectory.Open(new DirectoryInfo(BaseIndexDir.FullName + "\\Animal.1")), false);
            try
            {
                int num = reader.NumDocs();
                Assert.AreEqual(1, num);
            }
            finally
            {
                reader.Dispose();
            }

            tx = s.BeginTransaction();
            a = (Animal) await (s.GetAsync(typeof(Animal),1));
            a.Name = "Mouse";
            await (tx.CommitAsync());

            s.Clear();

            reader = IndexReader.Open(FSDirectory.Open(new DirectoryInfo(BaseIndexDir.FullName + "\\Animal.1")), false);
            try
            {
                int num = reader.NumDocs();
                Assert.AreEqual(1, num);
                TermDocs docs = reader.TermDocs(new Term("name", "mouse"));
                Assert.IsTrue(docs.Next());
                Document doc = reader.Document(docs.Doc);
                Assert.IsFalse(docs.Next());
            }
            finally
            {
                reader.Dispose();
            }

            tx = s.BeginTransaction();
            IFullTextSession fts = Search.CreateFullTextSession(s);
            QueryParser parser = new QueryParser(Version.LUCENE_30, "id", new StopAnalyzer(Version.LUCENE_30));

            IList results = await (fts.CreateFullTextQuery(parser.Parse("name:mouse OR name:bear")).ListAsync());
            Assert.AreEqual(2, results.Count, "Either double insert, single update, or query fails with shards");

            // cleanup
            await (s.DeleteAsync("from System.Object"));
            await (tx.CommitAsync());
            s.Close();
        }

        #endregion

        #region Setup/Teardown

        protected override void Configure(Configuration configuration)
        {
            base.Configure(configuration);

            // is the default when multiple shards are set up
            // configure.setProperty( "hibernate.search.Animal.sharding_strategy", IdHashShardingStrategy.class );
            configuration.SetProperty("hibernate.search.Animal.sharding_strategy.nbr_of_shards", "2");
            configuration.SetProperty("hibernate.search.Animal.0.indexName", "Animal00");
        }

        #endregion
    }
}