using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly : CLSCompliant(false)]
[assembly : AssemblyTitle("NHibernate.Search")]
[assembly : AssemblyDescriptionAttribute("NHibernate Search - Integration with Lucene.NET")]
[assembly : AssemblyCompanyAttribute("NHibernate.org")]
[assembly : AssemblyProductAttribute("NHibernate.Search")]
[assembly : AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly : AssemblyVersionAttribute("2.0.0.1001")]
[assembly : AssemblyInformationalVersionAttribute("2.0.0.1001")]
[assembly : AssemblyFileVersionAttribute("2.0.0.1001")]
//[assembly : AssemblyKeyFileAttribute("../../src/NHibernate.snk")]
[assembly : AssemblyDelaySignAttribute(false)]