//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using System.Collections.Generic;
using Lucene.Net.Analysis.Standard;
using Lucene.Net.QueryParsers.Classic;
using Lucene.Net.Util;
using NUnit.Framework;

namespace NHibernate.Search.Tests.Embedded
{
    using System.Threading.Tasks;
    /// <summary>
    /// The embedded test.
    /// </summary>
    [TestFixture]
    public class EmbeddedTestAsync : SearchTestCase
    {
        #region Helper methods

        // protected override void Configure(Configuration configuration)
        // {
        // base.Configure(configuration);
        // // TODO: Set up listeners!
        // }

        /// <summary>
        /// Gets Mappings.
        /// </summary>
        protected override IEnumerable<string> Mappings
        {
            get
            {
                return new[]
                           {
                           "Embedded.Tower.hbm.xml",
                           "Embedded.Address.hbm.xml",
                           "Embedded.Product.hbm.xml",
                           "Embedded.Order.hbm.xml",
                           "Embedded.Author.hbm.xml",
                           "Embedded.Country.hbm.xml"
                           };
            }
        }

        #endregion

        #region Tests

        /// <summary>
        /// The embedded indexing.
        /// </summary>
        [Test]
        public async Task EmbeddedIndexingAsync()
        {
            Tower tower = new Tower();
            tower.Name = "JBoss tower";
            Address a = new Address();
            a.Street = "Tower place";
            a.Towers.Add(tower);
            tower.Address = a;
            Owner o = new Owner();
            o.Name = "Atlanta Renting corp";
            a.OwnedBy = o;
            o.Address = a;
            Country c = new Country();
            c.Name = "France";
            a.Country = c;

            ISession s = OpenSession();
            ITransaction tx = s.BeginTransaction();
            await (s.PersistAsync(tower));
            await (tx.CommitAsync());

            IFullTextSession session = Search.CreateFullTextSession(s);
            QueryParser parser = new QueryParser(LuceneVersion.LUCENE_48, "id", new StandardAnalyzer(LuceneVersion.LUCENE_48));

            Lucene.Net.Search.Query query = parser.Parse("address.street:place");
            IList result = await (session.CreateFullTextQuery(query).ListAsync());
            Assert.AreEqual(1, result.Count, "unable to find property in embedded");

            query = parser.Parse("address.ownedBy_name:renting");
            result = await (session.CreateFullTextQuery(query).ListAsync());
            Assert.AreEqual(1, result.Count, "unable to find property in embedded");

            query = parser.Parse("address.id:" + a.Id);
            result = await (session.CreateFullTextQuery(query).ListAsync());
            Assert.AreEqual(1, result.Count, "unable to find property by id of embedded");

            query = parser.Parse("address.country.name:" + a.Country.Name);
            result = await (session.CreateFullTextQuery(query).ListAsync());
            Assert.AreEqual(1, result.Count, "unable to find property with 2 levels of embedded");

            s.Clear();

            tx = s.BeginTransaction();
            Address address = await (s.GetAsync<Address>(a.Id));
            address.OwnedBy.Name = "Buckhead community";

            // NB Not in the Java?
            await (s.PersistAsync(address));
            await (tx.CommitAsync());

            s.Clear();

            session = Search.CreateFullTextSession(s);

            query = parser.Parse("address.ownedBy_name:buckhead");
            result = await (session.CreateFullTextQuery(query).ListAsync());
            Assert.AreEqual(1, result.Count, "change in embedded not reflected in root index");

            s.Clear();

            // Tidy up
            tx = s.BeginTransaction();
            await (s.DeleteAsync(tower));
            await (s.DeleteAsync(a));
            await (s.DeleteAsync(c));
            await (tx.CommitAsync());

            s.Close();
        }

        /// <summary>
        /// The contained in.
        /// </summary>
        [Test]
        public async Task ContainedInAsync()
        {
            Tower tower = new Tower();
            tower.Name = "JBoss tower";
            Address a = new Address();
            a.Street = "Tower place";
            a.Towers.Add(tower);
            tower.Address = a;
            Owner o = new Owner();
            o.Name = "Atlanta Renting corp";
            a.OwnedBy = o;
            o.Address = a;

            ISession s = OpenSession();
            ITransaction tx = s.BeginTransaction();
            await (s.PersistAsync(tower));
            await (tx.CommitAsync());

            s.Clear();

            tx = s.BeginTransaction();
            Address address = await (s.GetAsync<Address>(a.Id));
            address.Street = "Peachtree Road NE";
            await (tx.CommitAsync());

            s.Clear();

            IFullTextSession session = Search.CreateFullTextSession(s);
            QueryParser parser = new QueryParser(LuceneVersion.LUCENE_48, "id", new StandardAnalyzer(LuceneVersion.LUCENE_48));

            Lucene.Net.Search.Query query = parser.Parse("address.street:peachtree");
            IList result = await (session.CreateFullTextQuery(query).ListAsync());
            Assert.AreEqual(1, result.Count, "change in embedded not reflected in root index");

            s.Clear();

            tx = s.BeginTransaction();
            address = await (s.GetAsync<Address>(a.Id));
            IEnumerator en = address.Towers.GetEnumerator();
            en.MoveNext();
            Tower tower1 = (Tower)en.Current;
            tower1.Address = null;
            address.Towers.Remove(tower1);
            await (tx.CommitAsync());

            s.Clear();

            session = Search.CreateFullTextSession(s);

            query = parser.Parse("address.street:peachtree");
            result = await (session.CreateFullTextQuery(query).ListAsync());
            Assert.AreEqual(0, result.Count, "breaking link fails");

            // Tidy up
            tx = s.BeginTransaction();
            await (s.DeleteAsync(tower));
            await (s.DeleteAsync(a));
            await (tx.CommitAsync());

            s.Close();
        }

        #endregion
    }
}