//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;

namespace NHibernate.Search.Engine
{
    using System.Threading.Tasks;
    using System.Threading;
    public partial interface ILoader
    {

        Task<object> LoadAsync(EntityInfo entityInfo, CancellationToken cancellationToken = default(CancellationToken));

        Task<IList> LoadAsync(EntityInfo[] entityInfos, CancellationToken cancellationToken = default(CancellationToken));
    }
}