name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - DB: SqlServer
            CONNECTION_STRING: "Server=localhost;User Id=sa;Password=P@ssw0rd;packet size=4096;"

    name: ${{matrix.DB}}

    steps:
    - name: Set up SqlServer
      if: matrix.DB == 'SqlServer'
      run: |
        docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=P@ssw0rd" -e "MSSQL_PID=Express" -p 1433:1433 -d --name sqlexpress mcr.microsoft.com/mssql/server:2019-latest;
    
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src/NHibernate.Search.sln

    - name: Build
      run: dotnet build src/NHibernate.Search.sln --no-restore

    - name: Configure
      run: |
        sudo apt-get install xmlstarlet -yy
        cp build-common/teamcity-hibernate.cfg.xml ./hibernate.cfg.xml
        xmlstarlet ed -L -N ns="urn:nhibernate-configuration-2.2" -u '//ns:property[@name="connection.connection_string"]' -v '${{matrix.CONNECTION_STRING}}' hibernate.cfg.xml        

    - name: Test
      run: dotnet test src/NHibernate.Search.sln -f net6.0 --no-build --verbosity normal
