name: test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build src -m:1 --no-restore

    - name: Configure
      run: cp build-common/teamcity-hibernate.cfg.xml ./hibernate.cfg.xml

    - name: Test
      run: dotnet test src -f net6.0 --no-build --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
